name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Update to v3

    - name: Setup Node.js
      uses: actions/setup-node@v3  # Update to v3
      with:
        node-version: '18'  # Using Node.js version 18

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # Branch to deploy to
        folder: dist  # Folder to deploy
        clean: true  # Automatically remove deleted files
